routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/', 'DashboardController@index')->name('home');

Route::get('/home', 'DashboardController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('/anggota', AnggotaController::class);
    Route::resource('/kategori', KategoriController::class);
    Route::resource('/penulis', PenulisController::class);
    Route::resource('/buku', BukuController::class);
    Route::resource('/peminjaman', PeminjamanController::class);

    Route::get('/dashboard','DashboardController@index')->name('dashboard');

    Route::get('/profile','ProfileController@edit')->name('profile');
    Route::post('/profile/{redirect}', 'ProfileController@update')->name('change-profile');

    Route::get('ubah-password', 'PasswordController@edit')->name('ubah-password');
    Route::post('ubah-password', 'PasswordController@update')->name('update-password');
    Route::get('/logout', 'HomeController@logout');
});

app/Peminjaman.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Peminjaman extends Model
{
    protected $table = "peminjaman";
    protected $fillable = ["id_buku", "id_anggota", "id_user", "tanggal_pinjam", "tanggal_kembali"];

    public function buku(){
        return $this->belongsTo('App\Buku','id_buku');
    }

    public function anggota(){
        return $this->belongsTo('App\Anggota','id_anggota');
    }

    public function user(){
        return $this->belongsTo('App\User','id_user');
    }
}

app/Http/Controllers/PeminjamanController.php
<?php

namespace App\Http\Controllers;

use App\Buku;
use App\User;
use App\Anggota;
use App\Peminjaman;
use Illuminate\Http\Request;

class PeminjamanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $peminjaman = Peminjaman::all();
        return view('peminjaman.index',compact('peminjaman'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $buku = Buku::all();
        $anggota = Anggota::all();
        $user = User::all();
        return view('peminjaman.create',compact('buku','anggota','user'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'buku' => 'required|string',
            'anggota' => 'required|string',
            'user' => 'required|string',
            'tanggal_pinjam' => 'required|date',
            'tanggal_kembali' => 'required|date|after:tanggal_pinjam'
        ]);

        Peminjaman::create([
            'id_buku' => $request->buku,
            'id_anggota' => $request->anggota,
            'id_user' => $request->user,
            'tanggal_pinjam' => $request->tanggal_pinjam,
            'tanggal_kembali' => $request->tanggal_kembali
        ]);
        return redirect('/peminjaman')->with('success','Data berhasil tersimpan!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $peminjaman = Peminjaman::where('id',$id)->get();
        return view('peminjaman.show',compact('peminjaman'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $buku = Buku::all();
        $anggota = Anggota::all();
        $user = User::all();
        $peminjaman = Peminjaman::findOrFail($id);
        return view('peminjaman.edit',compact('buku','anggota','user','peminjaman'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'buku' => 'required|string',
            'anggota' => 'required|string',
            'user' => 'required|string',
            'tanggal_pinjam' => 'required|date',
            'tanggal_kembali' => 'required|date|after:tanggal_pinjam'
        ]);

        $peminjaman = Peminjaman::where('id',$id)->update([
            'id_buku' => $request->buku,
            'id_anggota' => $request->anggota,
            'id_user' => $request->user,
            'tanggal_pinjam' => $request->tanggal_pinjam,
            'tanggal_kembali' => $request->tanggal_kembali
        ]);
        return redirect('/peminjaman')->with('success','Data berhasil tersimpan!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $peminjaman = Peminjaman::findOrFail($id);
        $peminjaman->delete();
        return redirect()->route('peminjaman.index')->with('success','Data berhasil dihapus!');
    }
}

resources/views/peminjaman/create.blade.php
@extends('layouts.master')
@push('style')
  <link rel="stylesheet" href="{{asset('assets/vendor/quill/dist/quill.core.css')}}" type="text/css">
@endpush

@section('content')
<div class="header bg-primary pb-6">
    <div class="container-fluid">
      <div class="header-body">
        <div class="row align-items-center py-4">
          <div class="col-lg-6 col-7">
            <h6 class="h2 text-white d-inline-block mb-0">Buku</h6>
            <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
              <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                <li class="breadcrumb-item"><a href="#"><i class="fas fa-home"></i></a></li>
                <li class="breadcrumb-item"><a href="#">Buku</a></li>
                <li class="breadcrumb-item active" aria-current="page">Tambah Data</li>
              </ol>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>
        <!-- Card stats -->
        <div class="container-fluid mt--6">

        <div class="row">
            <div class="col">
              <a href="{{ route('peminjaman.index') }}" class="btn btn-success mb-2 "> Kembali</a>
              <div class="card">
                <!-- Card header -->
                <div class="card-header border-0">
                  <h3 class="mb-0">Tambah Peminjam</h3>
                </div>

                <!-- Form -->
                <div class="container">
                    <form action="{{ route('peminjaman.store') }}" method="POST">
                        @csrf
                        <div class="form-group">
                            <label for="judul" class="form-control-label">Judul Buku</label>
                            <select name="buku" id="penulis" class="form-control">
                                <option value="">--Pilih Judul Buku--</option>
                                @foreach ($buku as $item => $value)
                                  <option value="{{ $value->id }}">{{ $value->judul }}</option>
                                @endforeach
                              </select>

                            @error('buku')
                            <div class="alert alert-danger">
                                {{ $message }}
                            </div>
                            @enderror

                        </div>
                        <div class="form-group">
                            <label for="anggota">Nama Anggota</label>
                            <select name="anggota" id="anggota" class="form-control">
                              <option value="">--Pilih Nama Anggota--</option>
                              @foreach ($anggota as $item => $value)
                                <option value="{{ $value->id }}">{{ $value->nama }}</option>
                              @endforeach
                            </select>

                            @error('anggota')
                            <div class="alert alert-danger">
                                {{ $message }}
                            </div>
                            @enderror

                        </div>

                        <div class="form-group">
                          <label for="user">Nama Petugas</label>
                          <select name="user" id="user" class="form-control">
                            <option value="">--Pilih Nama Petugas--</option>
                            @foreach ($user as $item => $value)
                              <option value="{{ $value->id }}">{{ $value->name }}</option>
                            @endforeach
                          </select>

                          @error('user')
                          <div class="alert alert-danger">
                              {{ $message }}
                          </div>
                          @enderror

                      </div>

                      <div class="form-group">
                        <label for="tanggal_pinjam" class="form-control-label">Tanggal Pinjam</label>
                        <input type="date" class="form-control" name="tanggal_pinjam">

                        @error('tanggal_pinjam')
                        <div class="alert alert-danger">
                            {{ $message }}
                        </div>
                        @enderror

                    </div>
                    <div class="form-group">
                        <label for="tanggal_kembali" class="form-control-label">Tanggal Kembali</label>
                        <input type="date" class="form-control" name="tanggal_kembali">

                        @error('tanggal_kembali')
                        <div class="alert alert-danger">
                            {{ $message }}
                        </div>
                        @enderror

                    </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">
                                {{ __('Tambah Data') }}
                            </button>
                        </div>
                    </form>
                </div>
              </div>
            </div>
          </div>
</div>
@endsection
@push('script')
  <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>

  <script type="text/javascript">
    tinymce.init({
      selector: '#mytextarea'
    });
    </script>
@endpush

resources/views/peminjaman/edit.blade.php
@extends('layouts.master')
@push('style')
  <link rel="stylesheet" href="{{asset('assets/vendor/quill/dist/quill.core.css')}}" type="text/css">
@endpush
@section('content')
<div class="header bg-primary pb-6">
    <div class="container-fluid">
      <div class="header-body">
        <div class="row align-items-center py-4">
          <div class="col-lg-6 col-7">
            <h6 class="h2 text-white d-inline-block mb-0">Peminjaman</h6>
            <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
              <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                <li class="breadcrumb-item"><a href="{{ route('home') }}"><i class="fas fa-home"></i></a></li>
                <li class="breadcrumb-item"><a href="{{ route('peminjaman.index') }}">Peminjaman</a></li>
                <li class="breadcrumb-item active" aria-current="page">Edit Data</li>
              </ol>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>
        <!-- Card stats -->
        <div class="container-fluid mt--6">

        <div class="row">
            <div class="col">
                <a href="{{ route('peminjaman.index') }}" class="btn btn-success mb-2 "> Kembali</a>
              <div class="card">
                <!-- Card header -->
                <div class="card-header border-0">
                  <h3 class="mb-0">Update Peminjaman</h3>
                </div>

                <!-- Form -->
                <div class="container">
                    <form action="{{ route('peminjaman.update',$peminjaman->id) }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                          <label for="buku" class="form-control-label">Judul Buku</label>
                          <select name="buku" id="buku" class="form-control">
                            <option value="">--Pilih Judul Buku--</option>
                            @foreach ($buku as $item => $value)
                              <option value="{{ $value->id }}"
                                @if ($peminjaman->id_buku == $value->id) selected="selected" @endif>{{ $value->judul }}</option>
                            @endforeach
                          </select>

                          @error('buku')
                          <div class="alert alert-danger">
                              {{ $message }}
                          </div>
                          @enderror

                      </div>

                    <div class="form-group">
                        <label for="anggota">Nama Anggota</label>
                        <select name="anggota" id="anggota" class="form-control">
                          <option value="">--Pilih Nama Anggota--</option>
                          @foreach ($anggota as $item => $value)
                            <option value="{{ $value->id }}"
                              @if ($peminjaman->id_anggota == $value->id) selected="selected" @endif>{{ $value->nama }}</option>
                          @endforeach
                        </select>

                        @error('anggota')
                        <div class="alert alert-danger">
                            {{ $message }}
                        </div>
                        @enderror

                    </div>

                    <div class="form-group">
                      <label for="user">Nama Petugas</label>
                      <select name="user" id="user" class="form-control">
                        <option value="">--Pilih Nama Petugas--</option>
                        @foreach ($user as $item => $value)
                          <option value="{{ $value->id }}"
                            @if ($peminjaman->id_user == $value->id) selected="selected" @endif>{{ $value->name }}</option>
                        @endforeach
                      </select>

                      @error('user')
                      <div class="alert alert-danger">
                          {{ $message }}
                      </div>
                      @enderror

                    <div class="form-group">
                        <label for="tanggal_pinjam" class="form-control-label">Tanggal Pinjam</label>
                        <input class="form-control" type="date" id="tanggal_pinjam" name="tanggal_pinjam" value="{{ $peminjaman->tanggal_pinjam }}" placeholder="Pilih Tahun">

                        @error('tanggal_pinjam')
                        <div class="alert alert-danger">
                            {{ $message }}
                        </div>
                        @enderror

                    </div>

                    <div class="form-group">
                        <label for="tanggal_kembali" class="form-control-label">Tanggal Kembali</label>
                        <input class="form-control" type="date" id="tanggal_kembali" name="tanggal_kembali" value="{{ $peminjaman->tanggal_kembali }}" placeholder="Pilih Tahun">

                        @error('tanggal_kembali')
                        <div class="alert alert-danger">
                            {{ $message }}
                        </div>
                        @enderror

                    </div>
                  </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">
                                {{ __('Update Data') }}
                            </button>
                        </div>
                    </form>
                </div>
              </div>
            </div>
          </div>
</div>
@endsection
@push('script')
  <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>

  <script type="text/javascript">
    tinymce.init({
      selector: '#mytextarea'
    });
    </script>
@endpush

resources/views/peminjaman/index.blade.php
@extends('layouts.master')
@push('style')
  <link rel="stylesheet" href="{{asset('assets/vendor/datatables.net-bs4/css/dataTables.bootstrap4.min.css')}}">
  <link rel="stylesheet" href="{{asset('assets/vendor/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css')}}">
  <link rel="stylesheet" href="{{asset('assets/vendor/datatables.net-select-bs4/css/select.bootstrap4.min.css')}}">
  <link rel="stylesheet" href="{{asset('assets/vendor/sweetalert2/dist/sweetalert2.min.css')}}">
@endpush

@section('content')
<div class="header bg-primary pb-6">
    <div class="container-fluid">
      <div class="header-body">
        <div class="row align-items-center py-4">
          <div class="col-lg-6 col-7">
            <h6 class="h2 text-white d-inline-block mb-0">Peminjaman</h6>
            <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
              <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                <li class="breadcrumb-item"><a href="{{ route('dashboard') }}"><i class="fas fa-home"></i></a></li>
                <li class="breadcrumb-item"><a href="#">Peminjaman</a></li>
                <li class="breadcrumb-item active" aria-current="page">Data</li>
              </ol>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>
        <!-- Card stats -->
        <div class="container-fluid mt--6">

        <div class="row">
          {{-- <div class="col-xl-12 m-4"> --}}
            <div class="col">
                <a href="{{ route('peminjaman.create') }}" class="btn btn-warning mb-2 ">+ Tambah Peminjam</a>
              <div class="card">
                <!-- Card header -->
                <div class="card-header border-0">
                  <h3 class="mb-0">Data Peminjaman</h3>
                </div>
                <!-- Light table -->
                <div class="table-responsive">
                  <table id="example1" class="table align-items-center table-flush">
                    <thead class="thead-light">
                      <tr>
                        <th scope="col" class="sort" data-sort="no">No</th>
                        <th scope="col" class="sort" data-sort="judul">Judul Buku</th>
                        <th scope="col" class="sort" data-sort="nama">Nama Anggota</th>
                        <th scope="col" class="sort" data-sort="name">Nama Petugas</th>
                        <th scope="col" class="sort" data-sort="tanggal_pinjam">Tanggal Pinjam</th>
                        <th scope="col" class="sort" data-sort="tanggal_kembali">Tanggal Kembali</th>
                        <th scope="col">Actions</th>
                      </tr>
                    </thead>
                    <tbody class="list">
                        @forelse ($peminjaman as $key => $value)
                        <tr>
                            <td>{{ $key + 1 }}</td>
                            <td>{{ substr($value->buku->judul,0,20) }} ...</td>
                            <td>{{ $value->anggota->nama }}</td>
                            <td>{{ $value->user->name }}</td>
                            <td>{{ $value->tanggal_pinjam }}</td>
                            <td>{{ $value->tanggal_kembali }}</td>
                            <td>
                                <form action="{{ route('peminjaman.destroy',$value->id) }}" method="POST">
                                    <a href="{{ route('peminjaman.show',$value->id) }}" class="btn btn-primary btn-sm">Show</a>
                                    <a href="{{ route('peminjaman.edit',$value->id) }}" class="btn btn-success btn-sm">Edit</a>
                                    @csrf
                                    @method('DELETE')
                                    <input type="submit" class="btn btn-danger btn-sm my-1" value="Delete">
                                </form>
                            </td>
                        </tr>
                        @empty
                        <tr scope="col">
                            <td>No data</td>
                        </tr>
                        @endforelse

                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
      </div>
        </div>
</div>
@endsection
@push('script')
  <script src="{{asset('assets/vendor/datatables.net/js/jquery.dataTables.min.js')}}"></script>
  <script src="{{asset('assets/vendor/datatables.net-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
  <script src="{{asset('assets/vendor/datatables.net-buttons/js/dataTables.buttons.min.js')}}"></script>
  <script src="{{asset('assets/vendor/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js')}}"></script>
  <script src="{{asset('assets/vendor/sweetalert2/dist/sweetalert2.min.js')}}"></script>
  <script>
    $(function () {
        $("#example1").DataTable();
    });

    @if (session('success'))
    swal.fire({
      title: 'Berhasil!',
      text: '{{ session('success') }}',
      buttonsStyling: false,
      confirmButtonClass: 'btn btn-success',
      icon: 'success'
    });
    @endif

  </script>
@endpush

resources/views/peminjaman/show.blade.php
@extends('layouts.master')

@section('content')
<div class="header bg-primary pb-6">
    <div class="container-fluid">
      <div class="header-body">
        <div class="row align-items-center py-4">
          <div class="col-lg-6 col-7">
            <h6 class="h2 text-white d-inline-block mb-0">Peminjaman</h6>
            <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
              <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                <li class="breadcrumb-item"><a href="{{ route('dashboard') }}"><i class="fas fa-home"></i></a></li>
                <li class="breadcrumb-item"><a href="{{ route('peminjaman.index') }}">Peminjaman</a></li>
                <li class="breadcrumb-item active" aria-current="page">Lihat Data</li>
              </ol>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>
        <!-- Card stats -->
        <div class="container-fluid mt--6">
        <div class="row">
            <div class="col">
                <a href="{{ route('peminjaman.index') }}" class="btn btn-success mb-2 "> Kembali</a>
              <div class="card">
                <!-- Card header -->
                <div class="card-header border-0">
                  <h3 class="mb-0">Data Peminjam</h3>
                </div>

                <!-- Form -->
                <div class="container">
                    @foreach ($peminjaman as $key => $value)
                    <form action="#">
                        <div class="form-group">
                            <label for="buku" class="form-control-label">Judul Buku</label>
                            <input class="form-control" type="text" id="buku" name="buku" value="{{ $value->buku->judul }}" disabled>
                        </div>
                        <div class="form-group">
                            <label for="anggota" class="form-control-label">Nama Anggota</label>
                            <input class="form-control" type="text" id="anggota" name="anggota" value="{{ $value->anggota->nama }}" disabled>
                        </div>
                        <div class="form-group">
                            <label for="user">Nama Petugas</label>
                            <input class="form-control" type="text" id="user" name="user" value="{{ $value->user->name }}" disabled>
                        </div>
                        <div class="form-group">
                          <label for="tanggal_pinjam">Tanggal Pinjam</label>
                          <input class="form-control" type="text" id="tanggal_pinjam" name="tanggal_pinjam" value="{{ $value->tanggal_pinjam }}" disabled>
                      </div>
                      <div class="form-group">
                        <label for="tanggal_kembali">Tanggal Kembali</label>
                        <input class="form-control" type="text" id="tanggal_kembali" name="tanggal_kembali" value="{{ $value->tanggal_kembali }}" disabled>
                    </div>
                    </form>
                    @endforeach
                </div>
              </div>
            </div>
          </div>
</div>
@endsection